version: '3.5'
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      # Needed for Traefik
      - "CONTAINERS=1"
      # Needed for certdumper
      - "POST=1"
      - "ALLOW_RESTARTS=1"
    ports:
      - '30000:2375'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - dockerproxy
  traefik:
    image: traefik:2.4
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.dnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.dnschallenge.acme.storage=acme.json"
      - "--certificatesresolvers.dnschallenge.acme.email=webmaster@example.com"  # <-- REPLACE
      - "--certificatesresolvers.dnschallenge.acme.dnschallenge.provider=namedotcom"  # <-- REPLACE, see https://doc.traefik.io/traefik/https/acme/#providers
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=anonaddy_default"  # default: <STACKNAME_NETWORK>, otherwise assign explicit network name
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    environment:
      - "NAMECOM_USERNAME_FILE=/run/secrets/namedotcom_username"  # <-- REPLACE, depends on your chosen DNS Challenge provider
      - "NAMECOM_API_TOKEN_FILE=/run/secrets/namedotcom_api_token"  # <-- REPLACE, depends on your chosen DNS Challenge provider
    networks:
      default:
        #ipv4_address: 172.20.0.2  <-- OPTIONAL, this can be customized when manually creating the network via `docker network create` CLI
      dockerproxy:
    depends_on:
      - dockerproxy
    secrets:
      - 
       source: EXAMPLEDOMAIN_NAMEDOTCOM_USERNAME
       target: /run/secrets/namedotcom_username
      - 
       source: EXAMPLEDOMAIN_NAMEDOTCOM_API_TOKEN
       target: /run/secrets/namedotcom_api_token
    volumes:
      - "./letsencrypt/acme.json:/acme.json"
    restart: always
  certdumper:
    image: humenius/traefik-certs-dumper:latest
    depends_on:
      - dockerproxy
      - traefik
    command: --restart-containers anonaddy
    volumes:
      - "./letsencrypt:/traefik:ro"
      - "./data/output:/output:rw"
    environment:
      - "DOCKER_HOST=dockerproxy:2375"
      #- "DOMAIN=anonaddy.example.com"  # <-- REPLACE (optional)
      - "OVERRIDE_UID=1000"
      - "OVERRIDE_GID=1000"
    networks:
      - dockerproxy
    restart: always
  anonaddy:
    image: anonaddy/anonaddy:latest
    depends_on:
      - db
      - redis
    container_name: anonaddy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anonaddy.entrypoints=https"
      - "traefik.http.routers.anonaddy.rule=Host(`anonaddy.example.com`)"  # <-- REPLACE
      - "traefik.http.routers.anonaddy.tls=true"
      - "traefik.http.routers.anonaddy.tls.certresolver=dnschallenge"
      - "traefik.http.routers.anonaddy.tls.domains[0].main=example.com"  # <-- REPLACE
      - "traefik.http.routers.anonaddy.tls.domains[0].sans=*.example.com"  # <-- REPLACE
      - "traefik.http.services.anonaddy.loadbalancer.server.port=8000"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    ports:
      - '25:25'
    volumes:
      - "./data:/data"
  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_PASSWORD"
      - "MYSQL_USER"
    volumes:
      - "./db:/var/lib/mysql"
    restart: always
  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always
secrets:
  EXAMPLEDOMAIN_NAMEDOTCOM_USERNAME:  # <-- REPLACE
    file: exampledomain_namedotcom_username.txt  # <-- REPLACE AND CREATE FILE
  EXAMPLEDOMAIN_NAMEDOTCOM_API_TOKEN:  # <-- REPLACE
    file: exampledomain_namedotcom_api_token.txt  # <-- REPLACE AND CREATE FILE
networks:
  dockerproxy:
    driver: bridge
    internal: true
