name: addy

services:
  db:
    image: mariadb:10
    container_name: addy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--ssl-ca=/etc/mysql/certs/${DB_SSL_CA}"
      - "--ssl-cert=/etc/mysql/certs/${DB_SSL_CERT}"
      - "--ssl-key=/etc/mysql/certs/${DB_SSL_KEY}"
    volumes:
      - "./db:/var/lib/mysql"
      - "./env:/etc/mysql/certs:ro"
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: addy_redis
    restart: always

  addy:
    image: anonaddy/anonaddy:latest
    container_name: addy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "./data:/data"
      - "./env:/env/certs"
    env_file:
      - "./addy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
